# Site settings
title: Angeleene (Zemmy) S. Ang
email: angeleene.ang@gmail.com
url: https://zemmyang.github.io
description: "Aspiring Physicist. Perpetually curious. Tries to be a bit of everything. Possibly secretly a starchy tuber."
keywords: #
skills: "Electro-optical Engineering PhD student"
meta_author: Ang Angeleenne Zemmy

google_verify: JQOCRSoMXTwd3OmZnLqdHZNchLxdJLHKEGnWwz1SDbw
contact: static

# Footer settings
footer:
  copyright: Angeleene Ang
  location: Current Location
  social: Around the Web
  credits: Theme Credits

# Social networks usernames
social:
  - title: fab fa-facebook-f
    url: https://www.facebook.com/ZemmyAng
  - title: fab fa-linkedin-in
    url: https://www.linkedin.com/in/zemmyang/
  - title: fab fa-pinterest-p
    url: http://pinterest.com/vardonir
  - title: fab fa-github-alt
    url: https://github.com/zemmyang
  - title: fab fa-steam
    url: https://steamcommunity.com/id/vardonir/

# Postal address (add as many lines as necessary)
address:
  - line: Be'er Sheva, Israel

# Credits content
credits: '<a href="http://startbootstrap.com">Freelancer</a> is a Bootstrap theme, adapted for Jekyll by <a href="https://github.com/jeromelachaud/freelancer-theme">jeromelachaud</a>. The version shown here is modified by <a href="https://github.com/zemmyanghttps://github.com/zemmyang">zemmyang</a>.'

# Build settings
markdown: kramdown
permalink: pretty
